title: Site
columns:
  # It reuses the pages section defined in `/site/blueprints/sections/albums.yml`
  - width: 1/3
    sections:
      albums:
        type: pages
        headline: Campaign Image Galleries
        parent: kirby.page("slideshow")
        info: "{{ page.images.count }} image(s)"
        layout: cardlets
        template: album
        empty: No albums yet
        image:
          cover: true
          query: page.previewImage
      galleries:
        type: pages
        headline: Campaign Image Galleries
        parent: kirby.page("galleries")
        info: "{{ page.images.count }} image(s)"
        layout: cardlets
        empty: No galleries yet
        image:
          cover: true
          query: page.previewImage
      slideshows:
        layout: list
        type: pages
        headline: Campaign Slideshows
        parent: kirby.page("slideshows")
      slides:
        layout: list
        type: pages
        headline: Campaign Web Slides
        parent: kirby.page("slides")
      opac:
        layout: list
        type: pages
        headline: OPAC Pages
        parent: kirby.page("opac")

  # The second column
  - width: 2/3
    label: Links
    type: structure
    fields:
      dslinks:
        extends: fields/links
        label: Digital Signage Links
      opaclinks:
        extends: fields/links
        label: OPAC Links
      otherlinks:
        extends: fields/links
        label: Other/Misc Links


