title: Site
columns:
  # It reuses the pages section defined in `/site/blueprints/sections/albums.yml`
  - width: 1/2
    sections:
      albums: sections/albums

      pages:
        layout: cardlets
        
        

  # The second column has two sections, `notes` and `pages`
  - width: 1/2
    label: Links
    type: structure
    fields:
      entries:
        extends: fields/dslinks
        label: Digital Signage Links